databases:
  - name: mon-blog-db
    plan: free
    databaseName: monblog
    user: monblog

services:
  - type: web
    name: mon-blog
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mon-blog-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
